default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [ layout1_setup.css, layout1_text.css ]
#  stylesheets:    [main.css]  

  javascripts:    []

  has_layout:     on
  layout:         layout1
