indexSuccess:
  metas:
    title:   Academia de Computación de Esime - Perfil de Profesores
    description: Información de los profesores de la academia de computación de Esime Zacatenco en la carrera de ICE
    