<?php


/**
 * This class adds structure of 'sf_guard_user_profile' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Jan 17 14:57:29 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PerfilMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PerfilMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PerfilPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PerfilPeer::TABLE_NAME);
		$tMap->setPhpName('Perfil');
		$tMap->setClassname('Perfil');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'sf_guard_user', 'ID', true, null);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 30);

		$tMap->addColumn('APELLIDO_PATERNO', 'ApellidoPaterno', 'VARCHAR', false, 30);

		$tMap->addColumn('APELLIDO_MATERNO', 'ApellidoMaterno', 'VARCHAR', false, 30);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 100);

		$tMap->addColumn('TELEFONO', 'Telefono', 'INTEGER', false, null);

		$tMap->addColumn('EXTENSION_1', 'Extension1', 'INTEGER', false, null);

		$tMap->addColumn('EXTENSION_2', 'Extension2', 'INTEGER', false, null);

		$tMap->addColumn('MOVIL', 'Movil', 'BIGINT', false, null);

		$tMap->addColumn('ESTANCIA', 'Estancia', 'VARCHAR', false, 30);

		$tMap->addColumn('HORARIO', 'Horario', 'VARCHAR', false, 30);

		$tMap->addColumn('FOTO', 'Foto', 'VARCHAR', false, 150);

		$tMap->addColumn('ENLACE', 'Enlace', 'VARCHAR', false, 50);

	} // doBuild()

} // PerfilMapBuilder
