<?php

/**
 * Base class that represents a row from the 'evaluacion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Jan 17 14:57:29 2010
 *
 * @package    lib.model.om
 */
abstract class BaseEvaluacion extends BaseObject  implements Persistent {


  const PEER = 'EvaluacionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EvaluacionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the profesor_id field.
	 * @var        int
	 */
	protected $profesor_id;

	/**
	 * The value for the pregunta_id field.
	 * @var        int
	 */
	protected $pregunta_id;

	/**
	 * The value for the num_resp_1 field.
	 * @var        int
	 */
	protected $num_resp_1;

	/**
	 * The value for the num_resp_2 field.
	 * @var        int
	 */
	protected $num_resp_2;

	/**
	 * The value for the num_resp_3 field.
	 * @var        int
	 */
	protected $num_resp_3;

	/**
	 * The value for the num_resp_4 field.
	 * @var        int
	 */
	protected $num_resp_4;

	/**
	 * The value for the num_resp_5 field.
	 * @var        int
	 */
	protected $num_resp_5;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * @var        Pregunta
	 */
	protected $aPregunta;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEvaluacion object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [profesor_id] column value.
	 * 
	 * @return     int
	 */
	public function getProfesorId()
	{
		return $this->profesor_id;
	}

	/**
	 * Get the [pregunta_id] column value.
	 * 
	 * @return     int
	 */
	public function getPreguntaId()
	{
		return $this->pregunta_id;
	}

	/**
	 * Get the [num_resp_1] column value.
	 * 
	 * @return     int
	 */
	public function getNumResp1()
	{
		return $this->num_resp_1;
	}

	/**
	 * Get the [num_resp_2] column value.
	 * 
	 * @return     int
	 */
	public function getNumResp2()
	{
		return $this->num_resp_2;
	}

	/**
	 * Get the [num_resp_3] column value.
	 * 
	 * @return     int
	 */
	public function getNumResp3()
	{
		return $this->num_resp_3;
	}

	/**
	 * Get the [num_resp_4] column value.
	 * 
	 * @return     int
	 */
	public function getNumResp4()
	{
		return $this->num_resp_4;
	}

	/**
	 * Get the [num_resp_5] column value.
	 * 
	 * @return     int
	 */
	public function getNumResp5()
	{
		return $this->num_resp_5;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EvaluacionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [profesor_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setProfesorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->profesor_id !== $v) {
			$this->profesor_id = $v;
			$this->modifiedColumns[] = EvaluacionPeer::PROFESOR_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setProfesorId()

	/**
	 * Set the value of [pregunta_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setPreguntaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pregunta_id !== $v) {
			$this->pregunta_id = $v;
			$this->modifiedColumns[] = EvaluacionPeer::PREGUNTA_ID;
		}

		if ($this->aPregunta !== null && $this->aPregunta->getId() !== $v) {
			$this->aPregunta = null;
		}

		return $this;
	} // setPreguntaId()

	/**
	 * Set the value of [num_resp_1] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setNumResp1($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->num_resp_1 !== $v) {
			$this->num_resp_1 = $v;
			$this->modifiedColumns[] = EvaluacionPeer::NUM_RESP_1;
		}

		return $this;
	} // setNumResp1()

	/**
	 * Set the value of [num_resp_2] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setNumResp2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->num_resp_2 !== $v) {
			$this->num_resp_2 = $v;
			$this->modifiedColumns[] = EvaluacionPeer::NUM_RESP_2;
		}

		return $this;
	} // setNumResp2()

	/**
	 * Set the value of [num_resp_3] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setNumResp3($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->num_resp_3 !== $v) {
			$this->num_resp_3 = $v;
			$this->modifiedColumns[] = EvaluacionPeer::NUM_RESP_3;
		}

		return $this;
	} // setNumResp3()

	/**
	 * Set the value of [num_resp_4] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setNumResp4($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->num_resp_4 !== $v) {
			$this->num_resp_4 = $v;
			$this->modifiedColumns[] = EvaluacionPeer::NUM_RESP_4;
		}

		return $this;
	} // setNumResp4()

	/**
	 * Set the value of [num_resp_5] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluacion The current object (for fluent API support)
	 */
	public function setNumResp5($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->num_resp_5 !== $v) {
			$this->num_resp_5 = $v;
			$this->modifiedColumns[] = EvaluacionPeer::NUM_RESP_5;
		}

		return $this;
	} // setNumResp5()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->profesor_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->pregunta_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->num_resp_1 = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->num_resp_2 = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->num_resp_3 = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->num_resp_4 = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->num_resp_5 = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = EvaluacionPeer::NUM_COLUMNS - EvaluacionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Evaluacion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfGuardUser !== null && $this->profesor_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
		if ($this->aPregunta !== null && $this->pregunta_id !== $this->aPregunta->getId()) {
			$this->aPregunta = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EvaluacionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EvaluacionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfGuardUser = null;
			$this->aPregunta = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEvaluacion:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EvaluacionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EvaluacionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEvaluacion:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEvaluacion:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EvaluacionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEvaluacion:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EvaluacionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->aPregunta !== null) {
				if ($this->aPregunta->isModified() || $this->aPregunta->isNew()) {
					$affectedRows += $this->aPregunta->save($con);
				}
				$this->setPregunta($this->aPregunta);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EvaluacionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EvaluacionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EvaluacionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}

			if ($this->aPregunta !== null) {
				if (!$this->aPregunta->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPregunta->getValidationFailures());
				}
			}


			if (($retval = EvaluacionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EvaluacionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getProfesorId();
				break;
			case 2:
				return $this->getPreguntaId();
				break;
			case 3:
				return $this->getNumResp1();
				break;
			case 4:
				return $this->getNumResp2();
				break;
			case 5:
				return $this->getNumResp3();
				break;
			case 6:
				return $this->getNumResp4();
				break;
			case 7:
				return $this->getNumResp5();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EvaluacionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getProfesorId(),
			$keys[2] => $this->getPreguntaId(),
			$keys[3] => $this->getNumResp1(),
			$keys[4] => $this->getNumResp2(),
			$keys[5] => $this->getNumResp3(),
			$keys[6] => $this->getNumResp4(),
			$keys[7] => $this->getNumResp5(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EvaluacionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setProfesorId($value);
				break;
			case 2:
				$this->setPreguntaId($value);
				break;
			case 3:
				$this->setNumResp1($value);
				break;
			case 4:
				$this->setNumResp2($value);
				break;
			case 5:
				$this->setNumResp3($value);
				break;
			case 6:
				$this->setNumResp4($value);
				break;
			case 7:
				$this->setNumResp5($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EvaluacionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setProfesorId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPreguntaId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNumResp1($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNumResp2($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setNumResp3($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNumResp4($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setNumResp5($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EvaluacionPeer::DATABASE_NAME);

		if ($this->isColumnModified(EvaluacionPeer::ID)) $criteria->add(EvaluacionPeer::ID, $this->id);
		if ($this->isColumnModified(EvaluacionPeer::PROFESOR_ID)) $criteria->add(EvaluacionPeer::PROFESOR_ID, $this->profesor_id);
		if ($this->isColumnModified(EvaluacionPeer::PREGUNTA_ID)) $criteria->add(EvaluacionPeer::PREGUNTA_ID, $this->pregunta_id);
		if ($this->isColumnModified(EvaluacionPeer::NUM_RESP_1)) $criteria->add(EvaluacionPeer::NUM_RESP_1, $this->num_resp_1);
		if ($this->isColumnModified(EvaluacionPeer::NUM_RESP_2)) $criteria->add(EvaluacionPeer::NUM_RESP_2, $this->num_resp_2);
		if ($this->isColumnModified(EvaluacionPeer::NUM_RESP_3)) $criteria->add(EvaluacionPeer::NUM_RESP_3, $this->num_resp_3);
		if ($this->isColumnModified(EvaluacionPeer::NUM_RESP_4)) $criteria->add(EvaluacionPeer::NUM_RESP_4, $this->num_resp_4);
		if ($this->isColumnModified(EvaluacionPeer::NUM_RESP_5)) $criteria->add(EvaluacionPeer::NUM_RESP_5, $this->num_resp_5);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EvaluacionPeer::DATABASE_NAME);

		$criteria->add(EvaluacionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Evaluacion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setProfesorId($this->profesor_id);

		$copyObj->setPreguntaId($this->pregunta_id);

		$copyObj->setNumResp1($this->num_resp_1);

		$copyObj->setNumResp2($this->num_resp_2);

		$copyObj->setNumResp3($this->num_resp_3);

		$copyObj->setNumResp4($this->num_resp_4);

		$copyObj->setNumResp5($this->num_resp_5);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Evaluacion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EvaluacionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EvaluacionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Evaluacion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setProfesorId(NULL);
		} else {
			$this->setProfesorId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addEvaluacion($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->profesor_id !== null)) {
			$c = new Criteria(sfGuardUserPeer::DATABASE_NAME);
			$c->add(sfGuardUserPeer::ID, $this->profesor_id);
			$this->asfGuardUser = sfGuardUserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addEvaluacions($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Declares an association between this object and a Pregunta object.
	 *
	 * @param      Pregunta $v
	 * @return     Evaluacion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPregunta(Pregunta $v = null)
	{
		if ($v === null) {
			$this->setPreguntaId(NULL);
		} else {
			$this->setPreguntaId($v->getId());
		}

		$this->aPregunta = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Pregunta object, it will not be re-added.
		if ($v !== null) {
			$v->addEvaluacion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Pregunta object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Pregunta The associated Pregunta object.
	 * @throws     PropelException
	 */
	public function getPregunta(PropelPDO $con = null)
	{
		if ($this->aPregunta === null && ($this->pregunta_id !== null)) {
			$c = new Criteria(PreguntaPeer::DATABASE_NAME);
			$c->add(PreguntaPeer::ID, $this->pregunta_id);
			$this->aPregunta = PreguntaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPregunta->addEvaluacions($this);
			 */
		}
		return $this->aPregunta;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->asfGuardUser = null;
			$this->aPregunta = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEvaluacion:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEvaluacion::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEvaluacion
