indexSuccess:
  metas:
    title: Academia de Computación de Esime - Sitios de Profesores
    description: Sitios de los profesores de la academia de computación de Esime Zacatenco en la carrera de ICE
    