indexSuccess:
  metas:
    title: Academia de Computación de Esime - Proyectos de Tesis
    description: Los proyectos de Tesis Curricular de la academia de computación de Esime Zacatenco en la carrera de ICE
    