indexSuccess:
  metas:
    title: Academia de Computación de Esime
    description: Academia de Computación de Esime Zacatenco del Instituto Politecnico Nacional en la Carrera de ICE

aboutSuccess:
  metas:
    title:  Academia de Computación de Esime - Desarrolladores
    description:  Los creadores del Portal Academico de ESIME Zacatenco

aresSuccess:
  metas:
    title: Academia de Computación de Esime - Ares R. Urbina Herrera
    description: Ares R. Urbina Herrera un estudiante de la generación 2004-2008 desarrollador de este portal
    

ricardoSuccess:
  metas:
    title: Academia de Computación de Esime - Ricardo Ortiz Cervantes
    description: Ricardo Ortiz Cervantes un estudiante de la generación 2004-2008 desarrollador de este portal

vicenteSuccess:
  metas:
    title: Academia de Computación de Esime -Vicente Mendoza Moreno
    description: Vicente Mendoza Moreno un estudiante de la generación 2004-2008 desarrollador de este portal
