generator:
  class: sfPropelGenerator
  param:
    model_class:           MateriaProfesor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          materia_profesor
    with_propel_route:     1
    css:                   generator

    config:
      actions: 
        _new:              { label: Nuevo }
        _edit:             { label: Editar }
        _delete:           { label: Borrar }
        _save:             { label: Guardar }
        _save_and_add:     { label: Guardar y Agregar }
        _list:             { label: Regresar }
      fields:
        sf_guard_user:     { label:  Profesor }
      list:
        peer_method:       doSelectJoinAll
        title:             Relación de Materias con sus respectivos Profesores
        display:           [=id, sf_guard_user, materia]
      filter:  ~
      form:    ~
      edit:  
        title:             Editar
      new:    
        title:             Nueva Relación
